---

  oracle_home_db: /u01/app/oracle/product/12.1.0.2/db_1
  oracle_stage: /u01/app/oracle/product/12.1.0.2/db_1
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_base: /u01/app/oracle
  configure_cluster: false

  oracle_databases:                                            # Dictionary describing the databases to be installed
        - home: db_1                                          # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
          oracle_version_db: 12.1.0.2                          # Oracle versiono
          oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
          oracle_db_name: orclans                                 # Database name
          oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
          oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
          is_container: "false"                                # (true/false) Is the database a container database
          pdb_prefix: pdb
          num_pdbs: 1
          storage_type: FS                                     # Database storage to be used. ASM or FS.
          service_name: orcl_serv                              # Inital service to be created (not in use yet)
          oracle_init_params: "open_cursors=300,processes=700" # Specific parameters to be set during installation. Comma-separated list
          oracle_db_mem_totalmb: 1024                          # Amount of RAM to be used for SGA + PGA
          oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
          redolog_size_in_mb: 100
          state: absent

    # DB
  default_dbpass: "{% if item.0.oracle_db_passwd is defined %}{{ item.0.oracle_db_passwd}}{% else %}Oracle123{% endif%}" # The check for the old passwords are there for  backwards compatibility and only temporary, will be removed
  dbpasswords:
         orclans:
           sys: Oracle_456
           system: Oracle_456
           dbsnmp: Oracle_456
           pdbadmin: Oracle_456
